# Generated by Django 4.1.13 on 2024-02-08 10:45

from django.db import migrations, models
import hospitals.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(max_length=100, validators=[hospitals.models.phone_number_validator]),
        ),
    ]
